#!/bin/bash
# Really bad code from 3 years ago.
# Fixed it up to make sure the server was working.
# Do not use.

SERVER=

#Pulling info from config file.
NUMBER=$(awk -F'=' '/^number/ {print $2}' ~/.sms_creds)
CARRIER=$(awk -F'=' '/^T/ {print $2}' ~/.sms_creds)

TIME=$1
shift 1

HOUR=$(echo ${TIME} | awk -F: '{print $1}')
MINUTE=$(echo ${TIME} | awk -F: '{print $2}')

if [ -z ${HOUR} ]; then
  HOUR=0
fi

MESSAGE=$@

cat << EOF

~~~~~~~~~~~ PAYLOAD ~~~~~~~~~~

Number: ${NUMBER}
Carrier: ${CARRIER}
Hour: ${HOUR}
Minute: ${MINUTE}
Message: ${MESSAGE}

EOF

curl \
  --data "number=${NUMBER}" \
  --data "carrier=${CARRIER}" \
  --data "hour=${HOUR}" \
  --data "minute=${MINUTE}" \
  --data "message=${MESSAGE}" \
  -skL ${SERVER}
